import type { Metadata } from "next";
import "./globals.css";
import { onest } from "@/src/shared/font";
import { ThemeProvider } from "../shared";
import { Toaster } from "../shared/components/ui/sonner";

export const metadata: Metadata = {
  title: "Shop Managament",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${onest.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster position="top-right" className="bg-background"/>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
