import type { Metadata } from "next";
import "./globals.css";
import { onest } from "@/src/shared/font";

export const metadata: Metadata = {
  title: "Shop Managament",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${onest.className} antialiased`}>{children}</body>
    </html>
  );
}
